### ISSUE TITLE
Pieces disappearing when using SVG

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#101]
Hi @grzegorz103 , it's me again :) I've tested a bit the [pieceIcons] input for the board, and while most of the time it works fine and it looks really nice, I noticed sometimes some of the pieces are missing. It didn't notice any particular pattern, just sometimes pieces are missing when the board is redrawn. Use for example the following svg for all pieces, you should see it happening. Any ideas what might cause this?
[whiteQueen.zip](https://github.com/grzegorz103/ngx-chess-board/files/5931775/whiteQueen.zip)

**Comment by grzegorz103** [comment]
Hello Robert :) I tried to recreate this and it works all time properly for me. I put Your icon in src/assets folder and in component I passed `whiteQueenUrl: '/assets/whiteQueen.svg',` Could You please check if there are any warnings/errors in devtools? Thanks

**Comment by RobertHajbok** [comment]
I did the same but with all pieces. Have a look at https://www.chessmeters.com, it’s using your package :) seems to be working fine right now, but noticed it on both desktop and mobile earlier today, at random moments.

**Comment by grzegorz103** [comment]
Seems working fine for me too, tried on mobile and desktop. I will be trying to recreate though. I leave this issue opened so if You notice anything please let me know. 

Btw dragging pieces on mobile doesn't work for me on Your site, or did you disable it for mobiles? In demo it is ok :)

**Comment by RobertHajbok** [comment]
Dragging works for me on Chrome for mobile, latest iOS. I didn’t disable it. I noticed it happening when it’s redrawing the entire board, if you reset it for example the white bishops are disappearing sometimes. Will let you know, maybe I manage to take a screenshot. Thanks!

**Comment by grzegorz103** [comment]
Hey Robert. I used custom icons for some time in a project and it was fine. I close this issue, but If you will notice anything let me know please :) thank you
