### ISSUE TITLE
An already started board

### ISSUE THREAD

**Issue by Michael-Aguirre-Merchan** [grzegorz103/ngx-chess-board#103]
Hi, @grzegorz103 

I was wondering if there is any way to set up a chessboard with a different fixed starting position and play it from there, something like this: 

![Image 1](https://user-images.githubusercontent.com/46231507/108233589-2edbe100-7101-11eb-920a-abb7e8364259.png)

**Comment by grzegorz103** [comment]
Hi @Michael-Aguirre-Merchan 
You can try to use `setFEN(fen: string)` method to set the board for your position. It is invoked at 60 line in `app.component.ts`  in the demo
