### ISSUE TITLE
Free Mode

### ISSUE THREAD

**Issue by ankitshahit** [grzegorz103/ngx-chess-board#104]
Hi, 

I came across this project, and really appreciate the hard-work! 

I was looking to add a free mode, which would not restrict based on player's turn.
I have done minor changes (can raise a pull request), and was wondering if you guys are open to add this as a feature. 
Please do let me know!

Thanks,
Ankit.

**Comment by grzegorz103** [comment]
Hello, free mod is very good idea :) create pull request please. Thanks

**Comment by ankitshahit** [comment]
Hi, Thank you!
I am trying to push the changes, but seems I dont have access to do so.

git push origin master:free-mode
remote: Permission to grzegorz103/ngx-chess-board.git denied to ankitshahit.
fatal: unable to access 'https://github.com/grzegorz103/ngx-chess-board.git/': The requested URL returned error: 403

**Comment by grzegorz103** [comment]
Hi Ankit. Try to fork the repo first, then commit to it and pull request from the fork to my repo. Should work, if it doesn't we will be thinking some other way

**Comment by ankitshahit** [comment]
Hi, 
Sure, let me try!

**Comment by grzegorz103** [comment]
Hi. Thanks, I merged to bbc4f4a26194a72d04826752bbe5b4da50511189
I fixed small thing that caused selecting piece after move again. It works perfect now :)

**Comment by ankitshahit** [comment]
Hi, 
Thanks for the help and opportunity! I hope to work again :)
