### ISSUE TITLE
possible move disable

### ISSUE THREAD

**Issue by ManojGaru** [grzegorz103/ngx-chess-board#112]
user needs to have a option disable possible move highlights and disable to move piece

**Comment by grzegorz103** [comment]
Hey. If you wanna disable possible move highlights you can try to use this
```
ngx-chess-board::ng-deep .possible-point {
    background: none;
}

ngx-chess-board::ng-deep .possible-point:hover {
    opacity: 1;
}
```
in your css. 

For disabling moves there are inputs ```[lightDisabled]``` and ```[darkDisabled]```. 

Let me know if this is what you are looking for

**Comment by ManojGaru** [comment]
Thank you @grzegorz103 for guiding.

**Comment by ManojGaru** [comment]
is there any way to to get the last move coords after uploading pgn ? I am getting the coords after moving a piece.
 Two scenario is there:
    1.after uploading PGN unable to get last move coord
    2. if putting a random player as the opponent then also unable to get last move coords

**Comment by grzegorz103** [comment]
PGN loading isn't implemented yet, did you mean FEN? If so then it doesn't provide any info about moves, so it's impossible to get last move coords after loading new position.

**Comment by ManojGaru** [comment]
Ok thank you, but it would be very helpful if can implemented last move coord after uploading a new postion.

**Comment by grzegorz103** [comment]
Yes but it can't be done with Fen
