### ISSUE TITLE
overwrite dest-move and source-move class

### ISSUE THREAD

**Issue by miradnan** [grzegorz103/ngx-chess-board#128]
Is there a way we can overwrite / disable highlight last move? 

It would be better if we can have a property that can be passed onto ngx-chess-board.

**Comment by grzegorz103** [comment]
There is a way to overwrite styles like this, but probably won't work as disabling:
```
ngx-chess-board::ng-deep .source-move {
    background: red !important;
}

ngx-chess-board::ng-deep .dest-move {
    background: blue !important;
}
```

Passing a property is very good idea. I been working on it already but haven't done yet. Will release it soon I guess :)

**Comment by miradnan** [comment]
Thats great to know. My requirement is not to have any background colour. It has to be optional setting.

**Comment by miradnan** [comment]
@grzegorz103 Maybe I can do this and send you a PR. But I couldn't find the css where the .source-move and .dest-move are defined. Can you help me locate it?

**Comment by grzegorz103** [comment]
73 and 77 line in ```ngx-chess-board.component.scss```. Currently colors are hard coded. I started making it as input so user could string provide like [sourcePoint]="background-color: green". If you would like feel to PR of course :)

**Comment by miradnan** [comment]
Hey, sent you a PR. Pls merge and update npm package.

**Comment by grzegorz103** [comment]
Done. thx, works perfectly

**Comment by miradnan** [comment]
That was quick. Thanks for merging.
