### ISSUE TITLE
Set fen position on page reload

### ISSUE THREAD

**Issue by miradnan** [grzegorz103/ngx-chess-board#141]
What is the recommended way to set fen position on page reload or navigation? I have tied ngOnInit but the board component isn't setup yet. I have tried other lifecycle hooks too. But they don't work either.

**Comment by grzegorz103** [comment]
I followed this comment https://stackoverflow.com/a/63010467/10693031 and worked for me like this:
```
export class AppComponent implements AfterContentChecked {

    constructor(private cdr: ChangeDetectorRef) {}

    ngAfterContentChecked(): void {
        this.cdr.detectChanges();
        this.boardManager.setFEN('rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1')
    }
```

Let me know if this works for you too

**Comment by miradnan** [comment]
Works well. Thanks!
