### ISSUE TITLE
Turn Off Square Highlighting

### ISSUE THREAD

**Issue by BenPearson95** [grzegorz103/ngx-chess-board#142]
How can I prevent the below squares from highlighting? I don't want the selected piece's square to be highlighted, and I don't want to show what pieces it is able to take?

![Capture](https://user-images.githubusercontent.com/17765082/117487317-d62f1e00-af62-11eb-80d7-5d1ca0036d77.PNG)

Here's the code I use to initialise the board, note the last 4 lines:
(showLastMove & showLegalMove are both equal to false in my component)
```
<ngx-chess-board 
              #board style="line-height: normal;"
              [size]="boardSize"
              [freeMode]="freeMode"
              [showCoords]="!showCoordsOutside && showCoordsInside"
              [lightTileColor]="colourFormGroup.value.darkColour"
              [darkTileColor]="colourFormGroup.value.lightColour"
              [sourcePointColor]="'none'"
              [destinationPointColor]="'none'"
              [showLastMove]="showLastMove"
              [showLegalMoves]="showLegalMove">
</ngx-chess-board>
```
Thanks!

**Comment by grzegorz103** [comment]
Hello Ben.
It was a small change so I added two inputs ```[showActivePiece]``` and ```[showPossibleCaptures]``` boolean as value.

That last 4 lines are about highlighting related to last move (source and destination move point)

Let me know if this works fine
