### ISSUE TITLE
PGN containing an en-passant move doesn't load properly

### ISSUE THREAD

**Issue by Akathian** [grzegorz103/ngx-chess-board#143]
When I try loading a PGN that has an en-passant move, the en-passant move and any subsequent moves are not loaded. Any moves preceding the en-passant are loading as expected though

Trying with the following PGN:
` "1. Nf3 Nc6 2. d4 Nf6 3. d5 Nb4 4. c4 Ne4 5. Nbd2 Nxd2 6. Bxd2 e5 7. e4 Qf6 8. a3 Na6 9. b4 Bd6 10. c5 Nxc5 11. bxc5 Bxc5 12. Qc2 Bb6 13. Bb4 a5 14. Bc5 Bxc5 15. Qxc5 b6 16. Qxc7 Qf4 17. Qxe5+ Qxe5 18. Nxe5 Bb7 19. Bb5 Rd8 20. Nc4 Kf8 21. Nxb6 d6 22. Rc1 Kg8 23. Rc7 Rb8 24. Nd7 Rd8 25. Rxb7 f5 26. exf5 h6 27. Kd2 Rh7 28. Rc1 Kh8 29. Rc6 g5 30. g6"` which has the FEN `"3r3k/1R1N3r/2Rp2Pp/pB1P4/8/P7/3K1PPP/8 b - - 0 30"`. 30. g6 is an en-passant move.
Expected board (what it should load): 
![image](https://user-images.githubusercontent.com/9373571/117554113-7cdaf380-b023-11eb-8600-5196781ff096.png)

Issue board (what actually is loaded): 
![image](https://user-images.githubusercontent.com/9373571/117554126-8c5a3c80-b023-11eb-9cad-e70f4e47a7cf.png)

Side note, your work is great, thank you for it. The best chessboard plugin I have found

**Comment by grzegorz103** [comment]
Hey. Thanks a lot for this issue. Indeed I forgot about en passant while loading PGN.
Bump package to 2.1.8 please and let me know if everything is okay please.
Thanks

**Comment by Akathian** [comment]
Works perfectly, thanks for the quick reply :)

**Comment by grzegorz103** [comment]
Very good, thanks :)
