### ISSUE TITLE
With 'FreeMode' True, Pieces can be positioned outside the board.

### ISSUE THREAD

**Issue by BenPearson95** [grzegorz103/ngx-chess-board#151]
It's me again!

Not sure if you're aware of this one... Or if it is intentional! Can't see it mentioned in the docs.

You are able to position a piece outside of the board with Free Mode enabled.

![image](https://user-images.githubusercontent.com/17765082/117879936-6fca3880-b29f-11eb-8dfd-4ba9f32ccf7e.png)

Cheers,

**Comment by grzegorz103** [comment]
Hey. Thanks a lot because this is very interesting issue, especially it happens only in free mode. I'm not sure why pieces aren't returning in origin place. I need to look at this closer because I didnt' realise it before

**Comment by grzegorz103** [comment]
Hello. I fixed this and now should be fine in v.2.1.10.
Thanks a lot for this issue
