### ISSUE TITLE
Get list of captured pieces

### ISSUE THREAD

**Issue by miradnan** [grzegorz103/ngx-chess-board#157]
Is there a way to get a list of captured moves?

**Comment by grzegorz103** [comment]
Not yet. But you can achieve similiar with extracting (moveChange) callback. The ```x``` field is true on piece capture and then save ```move``` field or extract it from PGN.

**Comment by miradnan** [comment]
@grzegorz103 is there a way I can get the piece colour in current position? I am trying to add colour to piece promotion

**Comment by grzegorz103** [comment]
@miradnan I think you can make a variable in your app, like whiteColor boolean and switch it with after moveChange callback.
But if you need to modify color or something, maybe you can give me some more details and i can implement some convinient way for your case

**Comment by miradnan** [comment]
@grzegorz103 thanks for the idea. I am basically looking for a way to identify if the current player in context is white or black. Let's say if the board is in default position the colour is white. If the board is reversed then the colour is black. A board component variable that will return the player colour. Maybe I can add a variable and send you a PR for review and merge.

**Comment by grzegorz103** [comment]
There are two properties in ```board.ts```
* ```reverted``` - it is true when black is at bottom (the board is reverted like the name says, because white are defaultly at bottom)
* ```currentWhitePlayer``` - says which color has to make move currently

If you want i can expose anything from it with some getter method. Let me know if it will fit your case please

**Comment by miradnan** [comment]
@grzegorz103 this works for me. Thanks.
