### ISSUE TITLE
Bug with possible captures

### ISSUE THREAD

**Issue by miradnan** [grzegorz103/ngx-chess-board#161]
There is a bug with possible captures. I have attached an image for reference.

Here are the steps to reproduce the bug.
Step 1: Move d2d4
Step 2: Move c7c5
Step 3: Move d4c5
Step 4: Move b7b5
Step 5: Move c5c6 // Now the bug would show the possible capture on b6 even though there is no piece there.

![Screenshot 2021-08-16 at 10 36 27 AM](https://user-images.githubusercontent.com/397415/129513799-806ab540-1690-459c-adab-3a1930293f18.png)

**Comment by grzegorz103** [comment]
Hey, thanks for the issue. The white pawn can capture on b6 because black moved his pawn as en passant move. If I'm wrong correct me please but I think this is fine :)

**Comment by miradnan** [comment]
Oops my bad. Thats correct.
