### ISSUE TITLE
Appears an extra bishop

### ISSUE THREAD

**Issue by OmarPelcastre** [grzegorz103/ngx-chess-board#166]
Sometimes appears a new bishop inside or outside of the board 
![Captura de Pantalla 2021-08-16 a la(s) 20 24 02](https://user-images.githubusercontent.com/29723772/129649060-7d74c8d4-cc40-4f0c-8da2-644cff29642e.png)

**Comment by grzegorz103** [comment]
Hi, thanks for this issue 

Can you please give me some more info, like when this bug happen? Is it always black bishop? Can this piece be moved, clicked or dragged? What inputs do you pass?

This would help me much in recreating this bug

**Comment by OmarPelcastre** [comment]
For example with this FEN "6k1/2p2ppp/pnp5/B7/2P3PP/1P1bPPR1/r6r/3R2K1 b - - 1 29" it always happen. Most times is just the black bishop but i think i have seen the bishop with a king too. You can drag the piece. if the piece appears inside of the board it can move, if it's outside it can't.

**Comment by grzegorz103** [comment]
Thanks a lot, indeed this happens. I will look into it

**Comment by grzegorz103** [comment]
In ```2.1.14``` shouldn't happen no more.

Thanks for this issue
