### ISSUE TITLE
Issue with the setPGN Method 

### ISSUE THREAD

**Issue by OmarPelcastre** [grzegorz103/ngx-chess-board#172]
I have been having problems with the setPGN method 
For example with this pgn:
1. e4 e6 2. d4 d5 3. Nd2 Nf6 4. Bd3 dxe4 5. Nxe4 Be7 6. c3 Nbd7 7. Nf3 c5 8. O-O O-O 9. Be3 cxd4 10. Nxd4 Nxe4 11. Bxe4 Nf6 12. Bc2 e5 13. Nf3 e4 14. Nd4 Bg4 15. Qd2 a6 16. h3 Bh5 17. Bb3 Bg6 18. f3 Bc5 19. Qe1 Re8 20. Rd1 Qb6 21. Qh4 exf3 22. Rxf3 Rad8 23. Qg5 Re7 24. Rdf1 Rde8 25. Kh1 Qc7 26. h4 Ne4 27. Qg4 Nf6 28. Qg5 Bd3 29. R1f2 Bxd4 30. cxd4 Bc4 31. Bxc4 Qxc4 32. h5 Ne4 33. Qg4 Nxf2+ 34. Rxf2 Rxe3 35. h6 Re1+ 36. Kh2 g6 37. Qf4 
the final position is different than the real one.

it does not happen with all pgn

**Comment by grzegorz103** [comment]
Hi. I fixed it. Bump to v2.1.16 and let me know everything is fine please. Thank you

**Comment by OmarPelcastre** [comment]
Thank you so much but now there's a problem when i set the pgn more than one time, it tries to make a new possible moves instead of reset the board and put it again, i don't know if you wanted to do it that way

**Comment by grzegorz103** [comment]
I'm not sure if i understand correctly. When you set a new pgn, the board's state is reseted, also possible moves array is cleared. I tried to set same/different pgns multiple times and didn't notice anything. Can you please explain a bit more how could i reproduce it? Thanks

**Comment by OmarPelcastre** [comment]
Sorry i was a mistake of my implementation. Everything is fine. Would you mine adding a premove function?

**Comment by grzegorz103** [comment]
Im glad you figured out what was wrong. I plan to implement premoves in future.

**Comment by OmarPelcastre** [comment]
I appreciate it a lot thank you
