### ISSUE TITLE
Unable to move same piece to original position after calling Undo()

### ISSUE THREAD

**Issue by BenPearson95** [grzegorz103/ngx-chess-board#174]
Hi again!

I'm running into this issue both in my environment and also on the demo page. When I move a piece, then undo() the move, and then attempt the same move again, it doesn't let me do that move, with no visible errors from my end. I am able to move the piece elsewhere though, it just prevents me from doing the same move again.

Cheers,

**Comment by grzegorz103** [comment]
Hi Ben. Thank you indeed there was a bug where you dragged a piece, then you couldnt move that piece again after undo. I fixed bump please to 2.1.17 and let me know please.

**Comment by BenPearson95** [comment]
Hi Grzegorz, 

Works perfectly, thank you.

Cheers,
