### ISSUE TITLE
Adding Piece to a Fresh Untouched Board causes Console Error 'setGamesStates'

### ISSUE THREAD

**Issue by BenPearson95** [grzegorz103/ngx-chess-board#176]
Hi Grzegorz,

Sorry to come at you with another issue. I greatly apprieciate all your help so far.

I'm able to replicate this on the demo board, and face the same issue in my app.

On the demo board, turn on FreeMode, and then add a piece onto the board, you will get a console error. Some functions will then not return the correct results, for example, getFen(), which will not give me the correct fen.

Moving a piece on the board before performing the above does not produce the console error, but ideally some scenarios in my app would not require a move to be played first.

Any issues, let me know.

Cheers,

**Comment by grzegorz103** [comment]
Hi. I fixed this by adding a nullcheck. Thank you and check please if it is fine now in 2.1.18

**Comment by BenPearson95** [comment]
Amazing, thank you very much :)
