### ISSUE TITLE
[showLastMove], [lightTileColor] and [darkTileColor]

### ISSUE THREAD

**Issue by ForceMax1** [grzegorz103/ngx-chess-board#221]
I can't get [showLastMove], [lightTileColor] and [darkTileColor] to work. 

`      <ngx-chess-board
            [showLastMove]="true"
            [darkTileColor]="0 0 0"
            [lightTileColor]="256 256 256"
            >
      </ngx-chess-board>`

What am I doing wrong?

**Comment by grzegorz103** [comment]
you try to pass like this:
[lightTileColor]="'black'" or [lightTileColor]="'#000000'"

**Comment by ForceMax1** [comment]
Thank you so much! Do you also know why the last move isn't displayed when I use the setFEN() method or how it is possible to display it?

**Comment by grzegorz103** [comment]
i think you can't see the last move in fen because it provides only piece's positions
you would have to use pgn instead

**Comment by ForceMax1** [comment]
Alright, thank you!
