### ISSUE TITLE
@angular/cdk dependency

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#89]
Hi! Just tried the package, but after installing it the Angular app stopped working. After building for production, it turned out @angular/cdk/drag-drop is required for ngx-chess-board to work. I'm using Angular version 11.0.8, I'm not sure this is an issue for previous versions, can this be fixed for future?

**Comment by grzegorz103** [comment]
Hey. @angular/cdk/drag-drop is added in peerDependencies in lib's package.json. User needs to install it by himself for now. I'm not sure if putting it as dependency (instead of peerDependency) to force automatic install will be good idea. Need to test it :) thanks
