### ISSUE TITLE
Kings next to each other

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#90]
Hi! Another bug I noticed, you can reach positions with kings on squares next to each other. For example 1.e3 e6 2.Ke2 Ke7 3.Kf3 Kf6 4.Ke4 and here Kf5 is allowed, while Ke5 is not allowed. After 4...Kf5, the white king is in check. Let me know if you need some pull requests, btw, nice work with this package!
![Kings](https://user-images.githubusercontent.com/5830487/104660476-892af180-56be-11eb-9e68-3a33f4952315.jpg)

**Comment by grzegorz103** [comment]
Fixed in 42658ce59b25f59a8bbc8404416fbae8e924e92b Thanks a lot

**Comment by RobertHajbok** [comment]
Works fine now, cheers!
