### ISSUE TITLE
Pawn promotions

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#91]
When promoting a pawn, the pieces you can choose from are not showing properly, last move by black was d2-d1, see below (the dark background is because of my Chrome setup).
![Promotion](https://user-images.githubusercontent.com/5830487/104775316-0f534080-5770-11eb-8dd8-a7ba9a7b7084.png)

**Comment by grzegorz103** [comment]
Fixed in 2.0.6, can you please specify what chrome setup you got for this dark modal background?

**Comment by RobertHajbok** [comment]
Will try in a bit, thanks 👍 Go to chrome://flags/ and enable "Force Dark Mode for Web Contents".

**Comment by RobertHajbok** [comment]
Images work now, looks a bit too big maybe 😄 
![Promotion](https://user-images.githubusercontent.com/5830487/104792141-543d9e00-5795-11eb-86b0-cbfa093d2f46.png)

**Comment by grzegorz103** [comment]
I will resize these images in next updates :) thank You for report
