### ISSUE TITLE
Suggestion - board resize

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#92]
As a suggestion, would it be possible to have something like lichess' board resize? I think it would be a very useful feature
![BoardResize](https://user-images.githubusercontent.com/5830487/105095829-1ba40a00-5a9e-11eb-81f9-8a127b191482.png)

**Comment by grzegorz103** [comment]
I planned to implement it already before but it finally got replaced with [size] input. Anyway maybe in time I will add such resizing. Thanks for suggestion
