### ISSUE TITLE
Load from PGN

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#97]
Hi @grzegorz103 , is there any possibility to load a game from PGN? If not, is there any chance to add this possibility? Let me know if you need a pull request on this. Thanks!

**Comment by grzegorz103** [comment]
HI @RobertHajbok there is a way to set the board from FEN, please have a look [at the demo](https://grzegorz103.github.io/ngx-chess-board/chess-board/index.html) here is an example. It calls setFEN() method on the board component

**Comment by RobertHajbok** [comment]
I saw the FEN method, but I'm talking about loading a full game with PGN. This is the common format in the chess community, FEN is used for loading a given position.

**Comment by grzegorz103** [comment]
Sorry I mixed them. Only FEN is implemented. PGN is probably going to be implemented in future
