### ISSUE TITLE
Flipping board twice

### ISSUE THREAD

**Issue by RobertHajbok** [grzegorz103/ngx-chess-board#98]
If you flip the board first time, you can see in the bottom left corner you have the h8 square. But if you flip the board back (you are white again), your bottom left corner is still h8, which is incorrect.

**Comment by grzegorz103** [comment]
Thanks. Fixed in a1cd1ab4deb7f484203022c0a012a4edff8c97fd, also fixed an similiar issue where board was reversed and you loaded FEN. Available in v2.0.7
